version: '2.1'

services:
  scribus:
    build: .
    image: scribus
    container_name: scribus
    volumes:
      - "data_work:/home/ubuntu"
      - "/home/demers/share:/home/ubuntu/share"
      - "/dev/shm:/dev/shm"
    #restart: always
    ports:
      - "22:22"
      - "6080:80"
      - "5900:5900"
    network_mode: "host"

volumes:
  data_work:
